
const string = 'CRIME_DATE,CRIME_YEAR,CRIME_CATEGORY_NUMBER,CRIME_CATEGORY_DESCRIPTION,STREET,CITY,STATE,ZIP,LATITUDE,LONGITUDE,REPORTING_DISTRICT,CRIME_IDENTIFIER,LOCATION';

console.log(string.toLowerCase());
